backend logic to update medication dosages and times
ES2-UFPI/Remedius pull request #62
Opened 2024-12-12 11:40 UTC by emerymoriconi

Implementação inicial dos métodos que contêm a lógica do backend para atualização de dosagens e horários das medicações, com métodos nas classes UsuarioMedicamentoService.java e UsuarioMedicamentoController.java.

2024-12-17 11:43 UTC, carlos-dani-dev requested changes
Retirar verificação do método PUT e devolver método POST ao Controller de UsuarioMedicamento

2024-12-19 11:21 UTC, LuisEnilton approved these changes

2024-12-19 11:21 UTC, LuisEnilton commented on backend/src/main/java/com/remedius/remedius/service/UsuarioMedicamentoService.java
> +    }
Tem como fazer os parâmetros serem opcionais, então se eu passar só a dosagem, ele atualiza ela e mantém o resto igual.

2024-12-19 11:24 UTC, carlos-dani-dev approved these changes

2024-12-19 11:24 UTC, merged